Repository openshift/images, pull requests merged in 2024-05, with the labels that each got.

#161 OCPBUGS-29593: Add "max_auto_priority" to keepalived configuration to remove NOTICE from logs
  ipfailover/keepalived/lib/config-generators.sh
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test, jira/severity-low, jira/valid-bug, jira/valid-reference

#168 [release-4.15] OCPBUGS-30413: update unit tests in egress/dns-proxy
  egress/dns-proxy/egress_dns_proxy_test.go
  go.mod
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#175 OCPBUGS-24850: Bump OpenShift 4.16, RHEL9, and iptables package
  egress/router/Dockerfile
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#176 OKD-210: Add the sig-nfv repo in the CS9 base
  base/Dockerfile.rhel9
Labels: lgtm, approved, jira/valid-reference

#177 OKD-210: Add sig-cloud repository and enable rt repository
  base/Dockerfile.rhel9
Labels: lgtm, approved, jira/valid-reference

#178 Add dnf-plugins-core in scos to help with OCP image compat
  base/Dockerfile.rhel9
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#179 OKD-40: Remove centos-openstack-zed and add in rdo repo to get python-cinderclient dependency
  base/Dockerfile.rhel9
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#180 OKD-40: Revert #179
  base/Dockerfile.rhel9
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
